### ISSUE TITLE
Deployment breaks on node-sass with a commit that doesn't relate to it.

### ISSUE THREAD

**Issue by Evanion** [mars/create-react-app-buildpack#35]
So, i was working on implementing redux-saga on my Heroku hosted app, and for some reason the build fails on heroku, but not anywhere else.
The latest commit fails (https://gitlab.com/saints-gaming/saints-web/commit/e112223f34a2a4321288877b8383eead10e97802):

`````
-----> React.js (create-react-app) multi app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git
=====> Detected Framework: Multipack
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_VERBOSE=false
       NODE_ENV=development
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  7.4.0
       engines.npm (package.json):   4.0.5
       
       Downloading and installing node 7.4.0...
       npm 4.0.5 already installed with node
       Resolving yarn version (latest) via semver.io...
       Downloading and installing yarn (0.20.3)...
       Installed yarn 0.20.3
-----> Restoring cache
       Loading 2 from cacheDirectories (default):
       - node_modules
       - bower_components (not cached - skipping)
-----> Building dependencies
       Installing node modules (yarn.lock)
       yarn install v0.20.3
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning fsevents@1.0.17: The platform "linux" is incompatible with this module.
       info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning "react-font-awesome@1.0.3" has incorrect peer dependency "react@~0.11.2".
       [4/4] Building fresh packages...
       Done in 30.68s.
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
=====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git
=====> Detected Framework: React.js (create-react-app)
       Using existing `static.json`
       Enabling runtime environment variables
> saints-react@0.1.0 build /tmp/build_e0ac4251c10c44bc36610fa84581cc4e
> npm run build-css && react-scripts build
> saints-react@0.1.0 build-css /tmp/build_e0ac4251c10c44bc36610fa84581cc4e
> node-sass src/ -o src/
fs.js:871
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^
Error: ENOENT: no such file or directory, scandir '/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:871:18)
    at Object.getInstalledBinaries (/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/node_modules/node-sass/lib/extensions.js:122:13)
    at foundBinariesList (/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
npm ERR! Linux 3.13.0-105-generic
npm ERR! argv "/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/.heroku/node/bin/node" "/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/.heroku/node/bin/npm" "run" "build-css"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! saints-react@0.1.0 build-css: `node-sass src/ -o src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saints-react@0.1.0 build-css script 'node-sass src/ -o src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the saints-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-sass src/ -o src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs saints-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls saints-react
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/build_e0ac4251c10c44bc36610fa84581cc4e/npm-debug.log
npm ERR! Linux 3.13.0-105-generic
npm ERR! argv "/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/.heroku/node/bin/node" "/tmp/build_e0ac4251c10c44bc36610fa84581cc4e/.heroku/node/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! saints-react@0.1.0 build: `npm run build-css && react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saints-react@0.1.0 build script 'npm run build-css && react-scripts build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the saints-react package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-css && react-scripts build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs saints-react
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls saints-react
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/build_e0ac4251c10c44bc36610fa84581cc4e/npm-debug.log
 !     Push rejected, failed to compile React.js (create-react-app) multi app.
 !     Push failed
`````

I'm completely at a loss at what is causing it ...
The commit before it works just fine 😕 : https://gitlab.com/saints-gaming/saints-web/commit/8fdf169b68fa8110390b0a3394bc5f54801b073b

**Comment by mars** [comment]
Looks like this is [a known problem with node-sass' native binary](https://github.com/sass/node-sass/issues/1579#issuecomment-227662011) that requires forcing a rebuild of node-sass to solve:

```
npm rebuild node-sass
```

It seems that npm does not automatically rebuild the native bins when it should.

For Heroku, prepend the `npm rebuild` command to `scripts.build` in **package.json**, for example:

```bash
npm rebuild node-sass && npm run build-css && react-scripts build
```

It's also possible that the clearing Node buildpack's build cache with [`repo:purge`](https://github.com/heroku/heroku-repo) would solve this, although my guess is that it would eventually go bad again when node-sass is upgraded.

**Comment by Evanion** [comment]
@mars Thank you! The rebuild step solved the issue!
I think you should add a section to the readme/wiki of these types of issues.
Just my two cents 👍

**Comment by mars** [comment]
Glad to hear that helped!

I just added a [Troubleshooting](https://github.com/mars/create-react-app-buildpack/blob/master/README.md#troubleshooting) section to the README. Hopefully that helps others along this winding path 🤓

**Comment by zachfedor** [comment]
Thanks for submitting the issue, @Evanion. I didn't catch the fix in the readme, but I found it here. I appreciate the fix, @mars!

**Comment by TaroWong** [comment]
Hi @mars , thanks for creating this buildpack! 

I am having trouble with something similar which is `node-sass-chokidar`. I have tried the similar solution which is to `npm rebuild node-sass-chokidar` but still fails to compile. 

This is my package.json
```
"dependencies": {
    "node-sass-chokidar": "^0.0.3",
    "normalize.css": "^7.0.0",
    "npm-run-all": "^4.1.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.0"
  },
  "scripts": {
    "build-css": "node-sass-chokidar src/ -o src/",
    "watch-css":
      "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build-js": "react-scripts build",
    "build": "npm-run-all build-css build-js",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }

```
Below is the error log
```
Counting objects: 60, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (56/56), done.
Writing objects: 100% (60/60), 116.37 KiB | 4.48 MiB/s, done.
Total 60 (delta 14), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> React.js (create-react-app) multi app detected
remote: -----> Configure create-react-app build environment
remote:        Using `NODE_ENV=development`
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-multi.git
remote: =====> Detected Framework: Multipack
remote: =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
remote: =====> Detected Framework: Node.js
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=false
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=development
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  unspecified
remote:        engines.npm (package.json):   unspecified (use default)
remote:        engines.yarn (package.json):  unspecified (use default)
remote:
remote:        Resolving node version 8.x...
remote:        Downloading and installing node 8.9.4...
remote:        Using default npm version: 5.6.0
remote:        Resolving yarn version 1.x...
remote:        Downloading and installing yarn (1.4.0)...
remote:        Installed yarn 1.4.0
remote:
remote: -----> Restoring cache
remote:        Skipping cache restore (not-found)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.4.0
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@1.1.3: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        info fsevents@1.1.2: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        [4/4] Building fresh packages...
remote:        Done in 24.76s.
remote:
remote: -----> Caching build
remote:        Clearing previous node cache
remote:        Saving 2 cacheDirectories (default):
remote:        - node_modules
remote:        - bower_components (nothing to cache)
remote:
remote: -----> Build succeeded!
remote: =====> Downloading Buildpack: https://github.com/mars/create-react-app-inner-buildpack.git
remote: =====> Detected Framework: React.js (create-react-app)
remote:        Writing `static.json` to support create-react-app
remote:        Enabling runtime environment variables
remote:
remote: > portfolio@0.1.0 build /tmp/build_e6f6d2ff692b4d72ddeef4e1e9ec676e
remote: > npm-run-all build-css build-js
remote:
remote:
remote: > portfolio@0.1.0 build-css /tmp/build_e6f6d2ff692b4d72ddeef4e1e9ec676e
remote: > node-sass-chokida src/ -o src/
remote:
remote: sh: 1: node-sass-chokida: not found
remote: npm ERR! file sh
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno ENOENT
remote: npm ERR! syscall spawn
remote: npm ERR! portfolio@0.1.0 build-css: `node-sass-chokida src/ -o src/`
remote: npm ERR! spawn ENOENT
remote: npm ERR!
remote: npm ERR! Failed at the portfolio@0.1.0 build-css script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2018-02-07T18_54_45_713Z-debug.log
remote: ERROR: "build-css" exited with 1.
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! portfolio@0.1.0 build: `npm-run-all build-css build-js`
remote: npm ERR! Exit status 1
remote: npm ERR!
remote: npm ERR! Failed at the portfolio@0.1.0 build script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /app/.npm/_logs/2018-02-07T18_54_45_732Z-debug.log
remote:  !     Push rejected, failed to compile React.js (create-react-app) multi app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to tarowong.
remote:
To https://git.heroku.com/tarowong.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/tarowong.git'

```

**Comment by mars** [comment]
@TaroWong npm bins do not automatically get added to the shell's $PATH, except for when they are globally installed `npm install -g package-name` or otherwise explicitly setup by the user.

Maybe try specifying the path to `node-sass-chokida` in the **package.json** script entry:

```
  "scripts": {
    "build-css": "`npm bin`/node-sass-chokidar src/ -o src/",
```

**Comment by TaroWong** [comment]
@mars Thank you so much for your prompt assistance! It works now. 😃 
I also just realized that there was a typo error. I forgot the "r".
